version: '3'

volumes:
  pgdata:
    driver: local

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
    - "80:8080"
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - python
  python:
    restart: always
    env_file:
      - env.env
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    expose:
      - 8000
    command: bash -c "./wait-for-postgres.sh && python manage.py makemigrations && python manage.py migrate && uwsgi --ini uwsgi.ini"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_django
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data